# Numpy -  multidimensional data arrays

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provides high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [ ]:
import numpy as np

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [ ]:
a = np.empty((5, 5), dtype=np.float32)
print(a)

[[-2.9788318e+03  3.3137906e-41  0.0000000e+00  0.0000000e+00
  -6.7985878e+29]
 [ 3.3143511e-41 -1.7992415e+20  4.3972746e-41 -6.7974816e+29
   3.3143511e-41]
 [-2.6145332e+21  4.3972746e-41 -2.6137766e+21  4.3972746e-41
  -6.8153798e+29]
 [ 3.3143511e-41 -1.1304024e+21  4.3972746e-41 -2.4446530e+21
   4.3972746e-41]
 [-1.8325231e+20  4.3972746e-41 -1.9483501e+20  4.3972746e-41
   2.0178698e-43]]


## Creating `numpy` arrays

From the [Numpy documentation](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html) we have that an _array_ is 

_An instance of class ndarray consists of a contiguous one-dimensional segment of computer memory (owned by the array, or by some other object), combined with an indexing scheme that maps N integers into the location of an item in the block._

Said differently, an array is mostly a contiguous block of memory whose parts can be accessed using an indexing scheme.

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [ ]:
# a vector: the argument to the array function is a Python list
v = np.array([1, 2, 3, 4])

v

array([1, 2, 3, 4])

In [ ]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1.0, 2.0], [3.2, 4.5]], dtype=np.float32)

M

array([[1. , 2. ],
       [3.2, 4.5]], dtype=float32)

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [ ]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [ ]:
v.shape

(4,)

In [ ]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [ ]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [ ]:
np.shape(M)

(2, 2)

In [ ]:
np.size(M)

4

In [ ]:
M.nbytes

16

In [ ]:
M.itemsize

4

**Remark.** If you are using IPython then you can see the content of the workspace using the `who` and `whos` commands. IPython is an interactive command-line terminal for Python. It was created by Fernando Perez in 2001. IPython offers an enhanced read-eval-print loop (REPL) environment particularly well adapted to scientific computing. In Jupyter you have Ipython!

In [ ]:
who

M	 a	 np	 v	 


In [ ]:
whos

Variable   Type       Data/Info
-------------------------------
M          ndarray    2x2: 4 elems, type `float32`, 16 bytes
a          ndarray    5x5: 25 elems, type `float32`, 100 bytes
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
v          ndarray    4: 4 elems, type `int64`, 32 bytes


So far the `numpy.ndarray` looks awfully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [ ]:
M.dtype

dtype('float32')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [ ]:
M[0, 0] = 1

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [ ]:
M = np.array([[1, 2], [3, 4]], dtype=np.int16)

M
M.dtype

dtype('int16')

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [ ]:
# create a range

x = np.arange(0, 10, 1)  # arguments: start, stop, step

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.arange(-1, 1, 0.1)
print(x)
help(np.arange)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
Help on built-in function arange in module numpy:

arange(
    start_or_stop,
    /,
    stop=None,
    step=1,
    *,
    dtype=None,
    device=None,
    like=None
)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(st

#### linspace and logspace

In [ ]:
# using linspace, both end points ARE included
print(np.linspace(0, 10, 10))
help(np.linspace)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
Help on method descriptor linspace in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(np.int_)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence co

In [ ]:
help(np.linspace)

Help on method descriptor linspace in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(np.int_)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
  

In [ ]:
print(np.logspace(0, 10, 11, base=np.e))
help(np.logspace)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
Help on method descriptor logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, 

#### mgrid

In [ ]:
x, y = np.mgrid[0:5, 0:5]  # similar to meshgrid in MATLAB

In [ ]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [ ]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### random data

In [ ]:
from numpy import random

In [ ]:
# uniform random numbers in [0,1]
random.rand(5, 5)

array([[0.45324117, 0.50052955, 0.52855947, 0.17412736, 0.44392395],
       [0.10556509, 0.94974469, 0.64290367, 0.07814181, 0.37121035],
       [0.51584722, 0.88457573, 0.037401  , 0.95938853, 0.71190814],
       [0.07040532, 0.10738745, 0.32645696, 0.04529217, 0.94912791],
       [0.39218667, 0.73152809, 0.637492  , 0.90114209, 0.92104407]])

In [ ]:
# standard normal distributed random numbers
random.randn(5, 5)

array([[-0.90381404,  0.18680816, -0.43978058,  0.48024867,  1.09711698],
       [ 1.3881092 ,  0.75622244,  0.20269333,  0.57075068, -0.70556509],
       [-1.09893598,  0.83162911, -0.32686736,  1.12687961,  0.2804752 ],
       [ 0.24668656,  0.23135162,  0.31280204, -0.14126189, -0.2779569 ],
       [ 1.88858883, -1.54711497,  0.74728617, -0.4834095 ,  0.52392477]])

In [ ]:
dir(random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

#### diag

In [ ]:
# a diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
# diagonal with offset from the main diagonal
np.diag([1, 2, 3], k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

#### zeros and ones

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## File I/O

### Comma-separated values (CSV)

A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` function.  

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [ ]:
M = random.rand(5, 5)

In [ ]:
np.savetxt("random-matrix.csv", M)
# help(np.savetxt)

In [ ]:
!cat random-matrix.csv

7.731743754560317372e-01 4.913291945880665645e-01 5.796719532633717309e-01 6.498324993025086371e-01 7.585430171629443663e-01
4.796470506036424331e-01 1.801564341064908481e-01 1.991265635982653048e-01 3.516687116598907759e-01 2.012402012006397900e-01
1.522540869811173092e-01 4.690228111477876549e-01 4.050060941236816037e-01 3.612875595236689774e-01 6.789618798626573248e-01
4.125993277858711616e-01 7.347833345937793137e-01 4.679161365789322735e-01 3.062788337967803365e-01 1.304155808787181847e-01
4.993211921542825005e-01 4.951897304502429487e-01 5.827897861718362993e-01 6.112419829059282383e-01 7.439038140740701355e-01


In [ ]:
!pwd

/home/user/lab_numgeo/lab/lab0


In [ ]:
A = np.genfromtxt("random-matrix.csv")
type(A)
# help(np.genfromtxt)

numpy.ndarray

In [ ]:
A

array([[0.77317438, 0.49132919, 0.57967195, 0.6498325 , 0.75854302],
       [0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ],
       [0.15225409, 0.46902281, 0.40500609, 0.36128756, 0.67896188],
       [0.41259933, 0.73478333, 0.46791614, 0.30627883, 0.13041558],
       [0.49932119, 0.49518973, 0.58278979, 0.61124198, 0.74390381]])

### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [ ]:
np.save("random-matrix.npy", M)

!file random-matrix.npy

/usr/bin/sh: 1: file: not found


In [ ]:
B = np.load("random-matrix.npy")
B

array([[0.77317438, 0.49132919, 0.57967195, 0.6498325 , 0.75854302],
       [0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ],
       [0.15225409, 0.46902281, 0.40500609, 0.36128756, 0.67896188],
       [0.41259933, 0.73478333, 0.46791614, 0.30627883, 0.13041558],
       [0.49932119, 0.49518973, 0.58278979, 0.61124198, 0.74390381]])

## More properties of the numpy arrays

In [ ]:
M.itemsize  # bytes per element

8

In [ ]:
M.nbytes  # number of bytes

200

In [ ]:
M.ndim  # number of dimensions

2

In [ ]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    5x5: 25 elems, type `float64`, 200 bytes
B          ndarray    5x5: 25 elems, type `float64`, 200 bytes
M          ndarray    5x5: 25 elems, type `float64`, 200 bytes
a          ndarray    5x5: 25 elems, type `float32`, 100 bytes
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
random     module     <module 'numpy.random' fr<...>umpy/random/__init__.py'>
v          ndarray    4: 4 elems, type `int64`, 32 bytes
x          ndarray    5x5: 25 elems, type `int64`, 200 bytes
y          ndarray    5x5: 25 elems, type `int64`, 200 bytes


## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [ ]:
# v is a vector, and has only one dimension, taking one index
v[0]

np.int64(1)

In [ ]:
# M is a matrix, or a 2 dimensional array, taking two indices
M

array([[0.77317438, 0.49132919, 0.57967195, 0.6498325 , 0.75854302],
       [0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ],
       [0.15225409, 0.46902281, 0.40500609, 0.36128756, 0.67896188],
       [0.41259933, 0.73478333, 0.46791614, 0.30627883, 0.13041558],
       [0.49932119, 0.49518973, 0.58278979, 0.61124198, 0.74390381]])

In [ ]:
M[1, 1]

np.float64(0.18015643410649085)

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [ ]:
M

array([[0.77317438, 0.49132919, 0.57967195, 0.6498325 , 0.75854302],
       [0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ],
       [0.15225409, 0.46902281, 0.40500609, 0.36128756, 0.67896188],
       [0.41259933, 0.73478333, 0.46791614, 0.30627883, 0.13041558],
       [0.49932119, 0.49518973, 0.58278979, 0.61124198, 0.74390381]])

In [ ]:
M[1]

array([0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ])

The same thing can be achieved with using `:` instead of an index: 

In [ ]:
M[1, :]  # row 1

array([0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ])

In [ ]:
M[:, 1]  # column 1

array([0.49132919, 0.18015643, 0.46902281, 0.73478333, 0.49518973])

We can assign new values to elements in an array using indexing:

In [ ]:
M[0, 0] = 1

In [ ]:
M

array([[1.        , 0.49132919, 0.57967195, 0.6498325 , 0.75854302],
       [0.47964705, 0.18015643, 0.19912656, 0.35166871, 0.2012402 ],
       [0.15225409, 0.46902281, 0.40500609, 0.36128756, 0.67896188],
       [0.41259933, 0.73478333, 0.46791614, 0.30627883, 0.13041558],
       [0.49932119, 0.49518973, 0.58278979, 0.61124198, 0.74390381]])

In [ ]:
# also works for rows and columns
M[1, :] = 0
M[:, 2] = -1

In [ ]:
M

array([[ 1.        ,  0.49132919, -1.        ,  0.6498325 ,  0.75854302],
       [ 0.        ,  0.        , -1.        ,  0.        ,  0.        ],
       [ 0.15225409,  0.46902281, -1.        ,  0.36128756,  0.67896188],
       [ 0.41259933,  0.73478333, -1.        ,  0.30627883,  0.13041558],
       [ 0.49932119,  0.49518973, -1.        ,  0.61124198,  0.74390381]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [ ]:
A = np.array([1, 2, 3, 4, 5])
A

array([1, 2, 3, 4, 5])

In [ ]:
A[1::2]

array([2, 4])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
A[1:3] = [-2, -3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [ ]:
A[::]  # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [ ]:
A[::2]  # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [ ]:
A[:3]  # first three elements

array([ 1, -2, -3])

In [ ]:
A[3:]  # elements from index 3

array([4, 5])

Negative indices count from the end of the array (positive index from the beginning):

In [ ]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


In [ ]:
A[-1]  # the last element in the array

np.int64(5)

In [ ]:
A[-3:]  # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [ ]:
A = np.array([[n + m * 10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
HH = np.array([[1.0 / (n + m + 1) for n in range(5)] for m in range(5)])

In [ ]:
HH

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [ ]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [ ]:
col_indices = [1, 2, -1]  # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [ ]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [ ]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [ ]:
# same thing
row_mask = np.array([5, 0, 1, 0, 0], dtype=bool)
print(row_mask)
B[row_mask]

[ True False  True False False]


array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
mask1 = 5 < x

mask2 = x < 7.5

mask1

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
mask2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [ ]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [ ]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [ ]:
index = np.arange(0, x.size)
index
index[mask]

array([11, 12, 13, 14])

**Exercise.** Sometimes in matrices we have missing values that can be represented either by NaN (`np.nan`) or Infinity (`np.inf`). Starting from the following matrix
$M=\left[\begin{matrix}
  1 & 2 & 3 & 4 \\
  3 & 4 & 5 & 6 \\
  5 & 6 & 7 & 8
\end{matrix}\right]$, substitute the element in position $(1,1)$ with `np.nan` and the element in position $(1,3)$ with `np.inf`. 
Use a mask to substitute all the occurrences of NaN and Inf with -1.

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [ ]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [ ]:
x[indices]  # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [ ]:
np.diag(A, -1)

array([10, 21, 32, 43])

### take

The `take` function is similar to fancy indexing described above:

In [ ]:
v2 = np.arange(-3, 3)
v2

array([-3, -2, -1,  0,  1,  2])

In [ ]:
row_indices = [1, 3, 5]
v2[row_indices]  # fancy indexing

array([-2,  0,  2])

In [ ]:
v2.take(row_indices)

array([-2,  0,  2])

But `take` also works on lists and other objects:

In [ ]:
np.take([-3, -2, -1, 0, 1, 2], row_indices)

array([-2,  0,  2])

### choose

Constructs an array by picking elements from several arrays:

In [ ]:
help(np.choose)

Help on method descriptor choose in module numpy:

choose(a, choices, out=None, mode='raise')
    Construct an array from an index array and a list of arrays to choose from.

    First of all, if confused or uncertain, definitely look at the Examples -
    in its full generality, this function is less simple than it might
    seem from the following code description::

        np.choose(a,c) == np.array([c[a[I]][I] for I in np.ndindex(a.shape)])

    But this omits some subtleties.  Here is a fully general summary:

    Given an "index" array (`a`) of integers and a sequence of ``n`` arrays
    (`choices`), `a` and each choice array are first broadcast, as necessary,
    to arrays of a common shape; calling these *Ba* and *Bchoices[i], i =
    0,...,n-1* we have that, necessarily, ``Ba.shape == Bchoices[i].shape``
    for each ``i``.  Then, a new array with shape ``Ba.shape`` is created as
    follows:

    * if ``mode='raise'`` (the default), then, first of all, each element of
      

In [ ]:
which = [1, 0, 1, 2]
choices = [[1, 2, 3, 4], [-5, -6, -7, -8], [9, 8, 65, 55]]

np.choose(which, choices)

array([-5,  2, -7, 55])

The first element of the result will be the first element of second "array" in choices; the second element
will be the second element of the first choice array, etc.

### Calculations with higher-dimensional data

When functions such as `min`, `max`, etc. are applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [ ]:
m = random.rand(3, 3)
m

array([[0.32786888, 0.20328101, 0.82476578],
       [0.15491667, 0.21020999, 0.33402336],
       [0.48170353, 0.60533931, 0.39964991]])

In [ ]:
# global max
m.max()

np.float64(0.8247657839760635)

In [ ]:
# max in each column
m.max(axis=0)

array([0.48170353, 0.60533931, 0.82476578])

In [ ]:
# max in each row
m.max(axis=1)

array([0.82476578, 0.33402336, 0.60533931])

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlying data, which makes it a fast operation even for large arrays.

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
n, m = A.shape
print(n, m)

5 5


In [ ]:
B = A.reshape((1, n * m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [ ]:
B[0, 0:5] = 5  # modify the array

B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [ ]:
A  # and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

In [ ]:
B = A.flatten()

B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [ ]:
B[0:5] = 10

B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [ ]:
A  # now A has not changed, because B's data is a copy of A's, not refering to the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

## Adding a new dimension: newaxis

With `newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [ ]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [ ]:
np.shape(v)

(3,)

In [ ]:
# make a column matrix of the vector v
vc = v[:, np.newaxis]
vc

array([[1],
       [2],
       [3]])

In [ ]:
# column matrix
v[:, np.newaxis].shape

(3, 1)

In [ ]:
# make a row matrix of the vector v
vr = v[np.newaxis, :]
vr

array([[1, 2, 3]])

In [ ]:
# row matrix
v[np.newaxis, :].shape

(1, 3)

In [ ]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1 + x2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
x1_new = x1[:, np.newaxis]

In [ ]:
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

## Stacking and repeating arrays

Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
# tile the matrix 3 times
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

### concatenate

In [ ]:
b = np.array([[5, 6]])
print(a, b)

[[1 2]
 [3 4]] [[5 6]]


In [ ]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### hstack and vstack

In [ ]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [ ]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [ ]:
# now B is referring to the same array data as A
B = A

In [ ]:
# changing B affects A
B[0, 0] = 10

B

array([[10,  2],
       [ 3,  4]])

In [ ]:
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [ ]:
B = np.copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0, 0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [ ]:
A

array([[10,  2],
       [ 3,  4]])

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an array:

In [ ]:
v = np.array([1, 2, 3, 4])

for element in v:
    print(element)

1
2
3
4


In [ ]:
M = np.array([[1, 2], [3, 4]])

for row in M:
    print("row", row)

    for element in row:
        print(element)

row [1 2]
1
2
row [3 4]
3
4


In [ ]:
M

array([[1, 2],
       [3, 4]])

When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)

    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)

        # update the matrix M: square each element
        M[row_idx, col_idx] = element**2

row_idx 0 row [1 2]
col_idx 0 element 1
col_idx 1 element 2
row_idx 1 row [3 4]
col_idx 0 element 3
col_idx 1 element 4


In [ ]:
# each element in M is now squared
M

array([[ 1,  4],
       [ 9, 16]])

## Using arrays in conditions

When using arrays in conditions, for example `if` statements and other boolean expressions, one needs to use `any` or `all`, which requires that any or all elements in the array evaluates to `True`:

In [ ]:
M

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

at least one element in M is larger than 5


In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5


## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [ ]:
M.dtype

dtype('int64')

In [ ]:
M = M.astype(complex)

M

array([[ 1.+0.j,  4.+0.j],
       [ 9.+0.j, 16.+0.j]])

In [ ]:
M.dtype

dtype('complex128')

In [ ]:
M3 = M.astype(float)

M3

/tmp/ipykernel_3297/4064403290.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  M3 = M.astype(float)


array([[ 1.,  4.],
       [ 9., 16.]])

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

In [ ]:
import numpy as np

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
v1 = np.arange(1, 4)
print(v1)
v2 = np.arange(3, 8)
print(v2)

[1 2 3]
[3 4 5 6 7]


In [ ]:
v1 * 2

array([2, 4, 6])

In [ ]:
v1 + 2

array([3, 4, 5])

In [ ]:
A = np.arange(0, 9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
A + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
A * A  # element-wise multiplication

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
v1 * v1

array([1, 4, 9])

If we multiply arrays with compatible shapes, we get an **element-wise** multiplication of each row:

In [ ]:
A.shape, v1.shape

((3, 3), (3,))

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
v1.shape

(3,)

In [ ]:
v1

array([1, 2, 3])

In [ ]:
A * v1

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

### Matrix algebra

#### Dot

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.dot(A, A)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [ ]:
np.dot(A, v1)

array([ 8, 26, 44])

In [ ]:
b = np.dot(v1, v1)
# type(b)
print(b)

14


Instead of using the function `np.dot` we can use `@` to perform the same operation

In [ ]:
A @ A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [ ]:
A @ v1

array([ 8, 26, 44])

In [ ]:
v1 @ v1

np.int64(14)

#### Matrix type (deprecated)

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra. The use of `matrix` is deprecated.

In [ ]:
help(np.matrix)

Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |
 |  matrix(data, dtype=None, copy=True)
 |
 |  Returns a matrix from an array-like object, or from a string of data.
 |
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the defau

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
M = np.matrix(A)
v = np.matrix(v1).T  # make it a column vector
print(M)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [2]
 [3]]


In [ ]:
M * M

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [ ]:
M * v

matrix([[ 8],
        [26],
        [44]])

In [ ]:
# inner product
v.T * v

matrix([[14]])

In [ ]:
# with matrix objects, standard matrix algebra applies
v + M * v

matrix([[ 9],
        [28],
        [47]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [ ]:
v = np.matrix([1, 2, 3, 4, 5, 6]).T
v

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
np.shape(M), np.shape(v)

((3, 3), (6, 1))

In [ ]:
M * v

ValueError: shapes (3,3) and (6,1) not aligned: 3 (dim 1) != 6 (dim 0)

#### Other commands

In [ ]:
help(np.cross)

Help on method descriptor cross in module numpy:

cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
    Return the cross product of two (arrays of) vectors.

    The cross product of `a` and `b` in :math:`R^3` is a vector perpendicular
    to both `a` and `b`.  If `a` and `b` are arrays of vectors, the vectors
    are defined by the last axis of `a` and `b` by default, and these axes
    must have 3 dimensions.

    Parameters
    ----------
    a : array_like
        Components of the first vector(s).
    b : array_like
        Components of the second vector(s).
    axisa : int, optional
        Axis of `a` that defines the vector(s).  By default, the last axis.
    axisb : int, optional
        Axis of `b` that defines the vector(s).  By default, the last axis.
    axisc : int, optional
        Axis of `c` containing the cross product vector(s).  By default, the last axis.
    axis : int, optional
        If defined, the axis of `a`, `b` and `c` that defines the vector(s)
       

In [ ]:
v3 = np.arange(0, 3)
v4 = np.array([1, 2, -1])
v5 = np.cross(v3, v4)
print(v5)

[-5  2 -1]


In [ ]:
np.dot(v3, v5)

np.int64(0)

In [ ]:
help(np.linalg.norm)

Help on method descriptor norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.

    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.

    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {int, float, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes`` for what values are
        supported for matrices and vectors respectively). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it speci

In [ ]:
print(v3)
np.linalg.norm(v3, 2)

[0 1 2]


np.float64(2.23606797749979)

In [ ]:
help(np.tensordot)

Help on method descriptor tensordot in module numpy:

tensordot(a, b, axes=2)
    Compute tensor dot product along specified axes.

    Given two tensors, `a` and `b`, and an array_like object containing
    two array_like objects, ``(a_axes, b_axes)``, sum the products of
    `a`'s and `b`'s elements (components) over the axes specified by
    ``a_axes`` and ``b_axes``. The third argument can be a single non-negative
    integer_like scalar, ``N``; if it is such, then the last ``N`` dimensions
    of `a` and the first ``N`` dimensions of `b` are summed over.

    Parameters
    ----------
    a, b : array_like
        Tensors to "dot".

    axes : int or (2,) array_like
        * integer_like
          If an int N, sum over the last N axes of `a` and the first N axes
          of `b` in order. The sizes of the corresponding axes must match.
        * (2,) array_like
          Or, a list of axes to be summed over, first sequence applying to `a`,
          second to `b`. Both elements a

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

### Array (and Matrix) transformations

Above we have used the `.T` to transpose the matrix object `v`. We could also have used the `transpose` function to accomplish the same thing. 

Other mathematical functions that transform matrix objects are:

In [ ]:
C = np.matrix([[1j, 2j], [3j, 4j]])  # deprecated
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [ ]:
C = np.array([[1j, 2j], [3j, 4j]])
C

array([[0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j]])

In [ ]:
np.conjugate(C)

array([[0.-1.j, 0.-2.j],
       [0.-3.j, 0.-4.j]])

Hermitian conjugate: transpose + conjugate

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag`:

In [ ]:
np.real(C)  # same as: C.real

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.imag(C)  # same as: C.imag

array([[1., 2.],
       [3., 4.]])

Or the complex argument and absolute value

In [ ]:
np.angle(C + 1)  # Warning MATLAB Users, angle is used instead of arg

array([[0.78539816, 1.10714872],
       [1.24904577, 1.32581766]])

In [ ]:
np.abs(C)

array([[1., 2.],
       [3., 4.]])

### Matrix computations

#### Inverse

In [ ]:
C.I  # if C is a matrix

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [ ]:
Cinv = np.linalg.inv(C)  # equivalent to C.I
Cinv

array([[0.+2.j , 0.-1.j ],
       [0.-1.5j, 0.+0.5j]])

In [ ]:
np.dot(Cinv, C)

array([[1.00000000e+00+0.j, 0.00000000e+00+0.j],
       [1.11022302e-16+0.j, 1.00000000e+00+0.j]])

In [ ]:
help(np.finfo)

Help on class finfo in module numpy:

class finfo(builtins.object)
 |  finfo(dtype)
 |
 |  finfo(dtype)
 |
 |  Machine limits for floating point types.
 |
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  dtype : dtype
 |      Returns the dtype for which `finfo` returns information. For complex
 |      input, the returned dtype is the associated ``float*`` dtype for its
 |      real and complex components.
 |  eps : float
 |      The difference between 1.0 and the next smallest representable float
 |      larger than 1.0. For example, for 64-bit binary floats in the IEEE-754
 |      standard, ``eps = 2**-52``, approximately 2.22e-16.
 |  epsneg : float
 |      The difference between 1.0 and the next smallest representable float
 |      less than 1.0. For example, for 64-bit binary floats in the IEEE-754
 |      standard, ``epsneg = 2**-53``, approximately 1.11e-16.
 |  iexp : int
 |      The number of bits in the exponent portion of the f

In [ ]:
print(np.finfo(float).eps)

2.220446049250313e-16


**Exercise 1.** Write a Python script to compute the `eps` value. 

#### Determinant

In [ ]:
np.linalg.det(C)

np.complex128(2.0000000000000004+0j)

In [ ]:
np.linalg.det(Cinv)

np.complex128(0.49999999999999967+0j)

### Solve linear system

To solve a linear system we can use the `linalg.solve` command which is a wrapper for the LAPACK routines `dgesv` and `zgesv`, the former being used if a is real-valued, the latter if it is complex-valued. The solution to the system of linear equations is computed using an LU decomposition with partial pivoting and row interchanges.

In [ ]:
help(np.linalg.solve)

Help on method descriptor solve in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.

    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.

    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.

    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is (..., M) if b is
        shape (M,) and (..., M, K) if b is (..., M, K), where the "..." part is
        broadcasted between a and b.

    Raises
    ------
    LinAlgError
        If `a` is singular or not square.

    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.

    Notes
    -----
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.

    The solutions are computed usi

In [ ]:
A = np.array([[1, 1], [1, 2]])
b = np.array([2, 3])
x = np.linalg.solve(A, b)
print(x)

[1. 1.]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([4, 5, 1])
x = np.linalg.solve(A, b)
print(x)

LinAlgError: Singular matrix

In [ ]:
np.linalg.det(A)

np.float64(0.0)

In [ ]:
help(np.linalg.cond)

Help on method descriptor cond in module numpy.linalg:

cond(x, p=None)
    Compute the condition number of a matrix.

    This function is capable of returning the condition number using
    one of seven different norms, depending on the value of `p` (see
    Parameters below).

    Parameters
    ----------
    x : (..., M, N) array_like
        The matrix whose condition number is sought.
    p : {None, 1, -1, 2, -2, inf, -inf, 'fro'}, optional
        Order of the norm used in the condition number computation:

        =====  ============================
        p      norm for matrices
        =====  ============================
        None   2-norm, computed directly using the ``SVD``
        'fro'  Frobenius norm
        inf    max(sum(abs(x), axis=1))
        -inf   min(sum(abs(x), axis=1))
        1      max(sum(abs(x), axis=0))
        -1     min(sum(abs(x), axis=0))
        2      2-norm (largest sing. value)
        -2     smallest singular value
        =====  ===========

In [ ]:
print(np.linalg.cond(A))

3.813147060626918e+16


**Exercise 1.** Write a Python function that takes two integer numbers `m` and `n` as input and creates the `m x n` Hilbert matrix. The Hilbert matrix has elements of the form `a[i,j]=1/(i+j-1)`. 

**Exercise 2.** Build a RHS vector for solving a linear system with the square Hilbert matrix of order `n` such that the solution is the vector of all 1. Solve the system for `n=5, 10, 100`.

**Exercise 3.** Build a RHS vector `b` for solving a linear system with the square Hilbert matrix (`H`) of order 5 such that the solution is the vector of all 1. Solve the system and get the solution `x`. Now perturb `b` with the vector `db=[0,0,0,0,1e-4]` and compute the new solution `x1`. Estimate the 2-norm condition number of `H` by means of 

\begin{equation}
\frac{\|x-x_1\|}{\|x\|}\leq \kappa_2 \frac{\|\delta b\|}{\|b\|}
\end{equation}

**Exercise 4.** Compute the condition number of the square Hilbert matrix for `n=5, 10, 100`.

### Eigenvalues and eigenvectors

Let A be an `n x n` matrix. The number &lambda; is an eigenvalue of `A` if there exists a non-zero vector `v` such that

Av = &lambda;v

In this case, vector `v` is called an eigenvector of `A` corresponding to &lambda;. You can use numpy to calculate the eigenvalues and eigenvectors of a matrix: 

In [ ]:
help(np.linalg.eig)

Help on method descriptor eig in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.

    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed

    Returns
    -------
    A namedtuple with the following attributes:

    eigenvalues : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs

    eigenvectors : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``eigenvectors[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``eigenvalues[i]``.

    Rais

In [ ]:
B = np.array([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])
print(np.linalg.det(B))
l, v = np.linalg.eig(B)
print(l)
print(v)

-90.0
[-5.+0.j  3.+0.j  6.+0.j]
[[ 0.81649658+0.j  0.53452248+0.j  0.05842062+0.j]
 [ 0.40824829+0.j -0.80178373+0.j  0.35052374+0.j]
 [-0.40824829+0.j -0.26726124+0.j  0.93472998+0.j]]


**Exercise 1.** Take a look at the document available at __[www.cs.huji.ac.il/~csip/tirgul2.pdf](http://www.cs.huji.ac.il/~csip/tirgul2.pdf)__ describing the power method for calculating the largest eigenvalue of a matrix. Write a Python function that takes as input the matrix `A`, the initial guess of the eigenvector `x0` and the maximum number of iteration `itmax` and returns the maximum eigenvalue and the corresponding eigenvector.

**Exercise 2.** Implement the inverse power method. This method is the original method applied to the matrix $A^{-1}$. With reference to the solution of Exercise 1 it must be noticed that in this case the computation of `q` (lines 3 and 9) requires the solution of a linear system (to this aim use `np.linalg.solve`). 

**Exercise 3.** Implement the inverse power method with shift. This method is the original method applied to the matrix $(A-\lambda I)^{-1}$; the user has to supply $\lambda$ (the _shift_ ) and the algorithm will find the closest eigenvalue to $\lambda$.

**Solution exercise 1.** 

In [ ]:
def eigpow(A, x0, itmax):
    x0 = x0 / np.linalg.norm(x0)
    q = np.dot(A, x0)
    lam = np.dot(x0, q)
    it = 0
    while it <= itmax:
        x = q
        x = x / np.linalg.norm(x)
        q = np.dot(A, x)
        lamnew = np.dot(x, q)
        lam = lamnew
        it = it + 1
    return lam, x

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

In [ ]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation

    Use ``default_rng()`` to create a `Generator` and call its methods.

    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================

    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    PCG64DXSM
    Philox
    SFC64
    ============================================= ===

    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------- ---
    SeedSe

In [ ]:
data = np.random.rand(100, 5)
data

array([[3.98288434e-01, 2.26789689e-01, 4.81893273e-01, 7.53919611e-01,
        6.15344195e-01],
       [1.15094867e-01, 2.21705317e-01, 6.59213407e-01, 7.55432117e-01,
        4.12358181e-01],
       [4.07177428e-01, 7.79367382e-01, 2.47839440e-01, 4.81703299e-01,
        9.27398311e-01],
       [8.33361921e-01, 2.31544040e-01, 1.90619979e-01, 7.39973604e-01,
        5.15218392e-01],
       [9.91224885e-01, 1.78484574e-01, 2.10455416e-01, 9.98193082e-01,
        1.60584433e-01],
       [1.00995235e-01, 4.96312194e-01, 5.17245256e-01, 2.48935694e-01,
        6.49684241e-01],
       [2.84976891e-01, 9.55655259e-01, 1.56132770e-01, 6.79241664e-01,
        7.73593931e-01],
       [6.72553547e-01, 9.10505639e-01, 7.30469321e-01, 1.96361410e-01,
        9.16644548e-01],
       [6.94065417e-01, 4.14035029e-01, 6.32878799e-01, 9.93721627e-01,
        6.47364640e-01],
       [1.93741200e-01, 6.28992831e-02, 5.12673107e-01, 7.08508077e-01,
        5.84104644e-01],
       [3.47191369e-01, 7.6238

#### mean

In [ ]:
# interesting data is in column 3
np.mean(data[:, 3])

np.float64(0.5043092234330254)

#### standard deviations and variance

In [ ]:
np.std(data[:, 3]), np.var(data[:, 3])

(np.float64(0.2929108296875155), np.float64(0.08579675414822871))

#### min and max

In [ ]:
# lowest value in column
data[:, 3].min()

np.float64(0.000697940684857401)

In [ ]:
# highest value in column
data[:, 3].max()

np.float64(0.9981930820420558)

In [ ]:
data1 = np.random.rand(5, 3)
data1

array([[0.82227425, 0.76284958, 0.79936504],
       [0.75084783, 0.68434321, 0.60485247],
       [0.38471031, 0.57208537, 0.05826714],
       [0.96307578, 0.44494899, 0.77776329],
       [0.39981276, 0.10971154, 0.92742005]])

In [ ]:
data1.min()

np.float64(0.05826714400562094)

#### sum, prod, and trace

In [ ]:
d = np.arange(1, 6)
d

array([1, 2, 3, 4, 5])

In [ ]:
# sum up all elements
sum(d)

np.int64(15)

In [ ]:
# product of all elements
np.prod(d)

np.int64(120)

In [ ]:
# cummulative sum
np.cumsum(d)

array([ 1,  3,  6, 10, 15])

In [ ]:
# cummulative product
np.cumprod(d)

array([  1,   2,   6,  24, 120])

In [ ]:
A = np.random.rand(5, 5)
# same as: diag(A).sum()
np.trace(A)

np.float64(3.4370886930843656)

#### Vectorization

As mentioned several times by now, to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [ ]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    # print(type(x))
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
Theta(-8)

0

In [ ]:
Theta(np.array([-3, -2, -1, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

OK, that didn't work because we didn't write the `Theta` function so that it can handle a vector input... 

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [ ]:
Theta_vec = np.vectorize(Theta)
Theta_vec

In [ ]:
Theta_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

In [ ]:
v = np.array([-3, -2, -1, 0, 1, 2, 3])
1.0 * (v >= 0)

array([0., 0., 0., 1., 1., 1., 1.])

We can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [ ]:
import numpy as np

In [ ]:
def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    # print(isinstance(x, np.ndarray))
    return 1 * (x >= 0)

In [ ]:
Theta(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

In [ ]:
# still works for scalars as well
Theta(-1.2), Theta(2.6)

(0, 1)